### DISCUSSION TITLE
long running LT against a single pod on eks cluster

### DISCUSSION THREAD

**Discussion by mamaigubasty** [fortio/fortio#659] [Q&A] [answered]
I never used Fortio before. 
The fortio pod was deployed in kube-system NS, with fortio container.
What should be container resources : CPU (request/limit) and Memory(request/limit)?
Should it have QoS= Guaranteed?
Is there a Demo which shows how to reach the container under test running on the same cluster in its NS?

Thanks,

Vitaly.

**Comment by ldemailly** [comment, marked as answer]
Are you using istio or something else on your k8s cluster?

Accessing fortio's web UI is similar to accessing any other service or app. For instance using istio ingress:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: fortio
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortio
  namespace: fortio
spec:
  selector:
    matchLabels:
      app: fortio
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
        - name: fortio
          image: fortio/fortio:latest_release
          args:
            - server
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 2000m
---
apiVersion: v1
kind: Service
metadata:
  name: fortio
  namespace: fortio
  labels:
    app: fortio
    service: fortio
spec:
  ports:
    - name: http2
      port: 8080
  selector:
    app: fortio
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: fortio-gateway
  namespace: fortio
spec:
  selector:
    istio: $INGRESS
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "fortio-$CLUSTER_ID.$REGION.$DOMAIN"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: echo
  namespace: echo
spec:
  hosts:
    - "fortio-$CLUSTER_ID.$REGION.$DOMAIN"
  gateways:
    - fortio-gateway
  http:
    - match:
        - headers:
            host:
              exact: "echo-$CLUSTER_ID.$REGION.$DOMAIN"
      route:
        - destination:
            host: fortio.echo.svc.cluster.local
            port:
              number: 8080
```

(in the above the namespace is fortio but can obviously be changed, not sure I'd put it in kube-system though)

For request/limit likewise it depends what you're going to be asking that pod to do - fortio does scale very well/near linearly with more cores and consumes very little memory

So if you wanted to generate >500k requests per second for instance (unlikely you need that many but...), you'd likely need at least 32-128 cores

Once deployed you can use the web UI or the new rest endpoints to generate load (they take same url params like url= qps= t= (time) etc... which mostly match the flag names you see running fortio help)

I haven't had to use QoS personally but it's an interesting thought
