### ISSUE TITLE
insecure https while using control UI

### ISSUE THREAD

**Issue by edussx** [fortio/fortio#315]
Hi,

I was using fortio control UI to trigger my test but found there's no place to specify `--https-insecure` option to use self-signed certs. I notice https://github.com/fortio/fortio/pull/138 has introduced the `--https-insecure` flag for CLI but didn't find anything in doc for using it in control UI. Is it currently supported?

Thanks!

**Comment by ldemailly** [comment]
the way to do that would be to start the server with that flag (it would then apply to all connections initiated from that server)

**Comment by edussx** [comment]
@ldemailly Thanks for the instruction...but it doesn't seem to work:
```
02:05:30 E http_client.go:326> Unable to send GET request for https://10.22.205.196/fortio1/?size=0 : Get https://10.22.205.196/fortio1/?size=0: x509: cannot validate certificate for 10.22.205.196 because it doesn't contain any IP SANs
```

And here is the fortio client container setup from my Deployment:
```
    spec:
      containers:
      - args:
        - server
        - -https-insecure
        command:
        - /usr/bin/fortio
        image: <my_private_registry_url>/fortio:latest_release
        imagePullPolicy: Always
        name: fortio
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      nodeSelector:
        fortio: client
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
```
So basically I started my fortio client with `fortio server -https-insecure` and triggered the test to `https://10.22.205.196/fortio1/?size=0` but fortio didn't ignore validating the cert...

I tried `curl -ik https://10.22.205.196/fortio1/?size=0` and it totally works:
```
# curl -ikv https://10.22.205.196:443/fortio1/?size=0
*   Trying 10.22.205.196...
* TCP_NODELAY set
* Connected to 10.22.205.196 (10.22.205.196) port 443 (#0)
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=CA; O=MyOrg, Inc.; CN=10.22.205.196
*  start date: Jan 24 10:06:10 2019 GMT
*  expire date: Jun  7 10:06:10 2020 GMT
*  issuer: C=CN
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /fortio1/?size=0 HTTP/1.1
> Host: 10.22.205.196
> User-Agent: curl/7.61.1
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< content-length: 0
content-length: 0
< content-type: application/octet-stream
content-type: application/octet-stream
< date: Fri, 25 Jan 2019 02:39:16 GMT
date: Fri, 25 Jan 2019 02:39:16 GMT
< x-envoy-upstream-service-time: 0
x-envoy-upstream-service-time: 0
< server: envoy
server: envoy

<
* Connection #0 to host 10.22.205.196 left intact
```
