### ISSUE TITLE
QPS can't exceed 450 on Openshift

### ISSUE THREAD

**Issue by erable2** [fortio/fortio#488]
I try to send many requests to an HTTP application but fortio can't exceed approximately 450 req/s.

**Plateform** : Openshift
**Control Plane configuration** :
```
proxy:
    runtime:
      container:
        resources:
          requests:
            cpu: 600m
            memory: 50Mi
          limits: {}

  runtime:
    components:
      pilot:
        container:
          resources:
            requests:
              cpu: 1000m
              memory: 1.6Gi
            limits: {}
```

Does Istio put a L7 rate limit by defaut ?
