### ISSUE TITLE
The possibility to randomise URL

### ISSUE THREAD

**Issue by franpog859** [fortio/fortio#879]
Is there a way to run Fortio for randomized URLs? For example, I want to run it for random IDs in this URL: `http://pod.namespace.svc.cluster.local:8080/things/123RANDOMID456/update`. I tried different things but nothing worked. Any help would be much appreciated!

I'm running it on Kubernetes, to do so I use this Job definition:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: fortio-job
  namespace: namespace
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - command:
            - fortio
            - load
            - -json
            - '-'
            - -content-type
            - application/json
            - -t
            - 60s
            - -qps
            - "500"
            - -c
            - "24"
            - -payload
            - '{"key":"value"}'
            - http://pod.namespace.svc.cluster.local:8080/things/123RANDOMID456/update
          image: fortio/fortio:1.20.0
          imagePullPolicy: IfNotPresent
          name: fortio
```
