### ISSUE TITLE
NaN in data cause json serialization to fatal

### ISSUE THREAD

**Issue by fawadkhaliq** [fortio/fortio#97]
fortio version: docker package->istio/fortio:latest from 01/23/2018

18:11:12 F fortio_main.go:273> Unable to json serialize result: json: unsupported value: NaN
panic: aborting...
goroutine 1 [running]:
istio.io/fortio/log.logPrintf(0x6, 0x931b21, 0x23, 0xc420205a50, 0x1, 0x1)
	/go/src/istio.io/fortio/log/logger.go:160 +0x28c
istio.io/fortio/log.Fatalf(0x931b21, 0x23, 0xc420205a50, 0x1, 0x1)
	/go/src/istio.io/fortio/log/logger.go:208 +0x5c
main.fortioLoad()
	/go/src/istio.io/fortio/fortio_main.go:273 +0xb5c
main.main()
	/go/src/istio.io/fortio/fortio_main.go:144 +0x669

**Comment by ldemailly** [comment]
@fawadkhaliq do you have an example of how to trigger/reproduce this ? which field is nan ?

**Comment by fawadkhaliq** [comment]
I noticed 4-5 times over tens of runs and before that I didn't pay attention to failure types so maybe it happens more often that I say. In any case, its definitely random. Each test run is similar to the following:

fortio->lwan 
qps = 1000 to 150000
duration = 10s to 60s
thread=8 to 10

fortio config
```apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fortio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fortio
    spec:
      containers:
      - image: istio/fortio
        imagePullPolicy: IfNotPresent
        name: fortio
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "2"
```

lwan config
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: lwan
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: lwan
    spec:
      containers:
      - image: jaxgeller/lwan
        imagePullPolicy: IfNotPresent
        name: lwan
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: lwan
  labels:
    app: lwan
spec:
  ports:
  - name: lwan
    port: 8080
  selector:
    app: lwan
```

As for the field, it is in response body type. See highlighted below:
Response Body/Total Sizes : count 599713 avg 1281 **+/- NaN** min 1281 max 1281 sum 768232353

Let me know if you need more information in case I see it again.
